# Generated by Django 5.2.13 on 2026-04-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_score',
            field=models.IntegerField(default=0, help_text='Score generated by AI matching'),
        ),
    ]
