# Generated by Django 5.2.13 on 2026-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
