from django.db import models
import uuid


class Application(models.Model):
    
    ai_score = models.IntegerField(default=0, help_text="Score generated by AI matching")
    
    ai_analysis = models.TextField(blank=True, null=True) 

    def __str__(self):
        return f"{self.candidate.email} - {self.job.title} ({self.ai_score}%)"

    @property
    def get_analysis_report(self):
        """
        Helper to quickly grab the AI report if the interview is done.
        """
        from interviews.models import InterviewSession
        from ai_analysis.models import AIAnalysis
        
        session = InterviewSession.objects.filter(application=self).first()
        if session:
            return AIAnalysis.objects.filter(interview=session).first()
        return None

    class Status(models.TextChoices):
        APPLIED = "applied"
        SHORTLISTED = "shortlisted"
        REJECTED = "rejected"
        INTERVIEW = "interview"
        HIRED = "hired"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    candidate = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        related_name="applications"
    )

    job = models.ForeignKey(
        "jobs.JobPosting",
        on_delete=models.CASCADE,
        related_name="applications"
    )

    resume = models.ForeignKey(
        "resumes.Resume",
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.APPLIED
    )

    cover_letter = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.candidate} → {self.job}"