# Generated by Django 5.2.13 on 2026-04-17 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('english_score', models.FloatField()),
                ('experience_score', models.FloatField()),
                ('communication_score', models.FloatField()),
                ('overall_score', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewsession')),
            ],
        ),
    ]
