# Generated by Django 5.2.13 on 2026-04-18 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='communication_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='english_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='experience_score',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='overall_score',
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='avg_english_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='avg_relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='candidate_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='overall_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='interview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='interviews.interviewsession'),
        ),
    ]
