# Generated by Django 5.2.13 on 2026-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_remove_aianalysis_communication_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='communication_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='detailed_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='technical_score',
            field=models.FloatField(default=0.0),
        ),
    ]
