# Generated by Django 5.2.13 on 2026-04-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0003_aianalysis_communication_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
    ]
