# Generated by Django 5.2.13 on 2026-04-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='total_experience',
            field=models.FloatField(default=0),
        ),
    ]
