# Generated by Django 5.2.13 on 2026-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_candidateprofile_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
