# Generated by Django 5.2.13 on 2026-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_candidateprofile_location_hrprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
