# Generated by Django 5.2.13 on 2026-04-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_candidateprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
