# Generated by Django 5.2.13 on 2026-04-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewanswer',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to='interview_audio/'),
        ),
        migrations.AlterField(
            model_name='interviewanswer',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='interview_videos/'),
        ),
    ]
